[package]
name = "prlents"
version = "0.1.0"
edition = "2021"
exclude = [
    "parser.rs",
    "merge_tags.rs"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

clap = { version = "4.3", features = ["derive"] }

